services:
  omp-server-mysql:
    container_name: omp-server-mysql
    image: mysql:5.6.51
    restart: unless-stopped
    platform: linux/amd64
    environment:
      - MYSQL_DATABASE=${MYSQL_HOST_AND_NAME_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./../sql-files/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./../volumes/mysql_data:/var/lib/mysql
    expose:
      - ${MYSQL_PORT}
    networks:
      - omp-network

  omp-server-pma:
    container_name: omp-server-pma
    image: phpmyadmin
    restart: unless-stopped
    platform: linux/amd64
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=${MYSQL_HOST_AND_NAME_DATABASE}
      - PMA_PORT=${MYSQL_PORT}
    expose:
      - ${PMA_INTERNAL_PORT}
    ports:
      - ${PMA_EXTERNAL_PORT}:${PMA_INTERNAL_PORT}
    networks:
      - omp-network
    depends_on:
      - omp-server-mysql

  omp-server-service:
    container_name: omp-server-service
    build:
      context: ./../../
      dockerfile: ./docker/dockerfiles/Dockerfile.omp.development
      args:
        OMP_DYNSSL: ${OMP_DYNSSL}
        PAWN_VERSION: ${PAWN_VERSION}
        OMP_VERSION: ${OMP_VERSION}
        OMP_SERVER_PORT: ${OMP_SERVER_PORT}
    restart: unless-stopped
    platform: linux/amd64
    volumes:
      - ./../../omp-server/components:/omp-server-service/omp-server/components:rw
      - ./../../omp-server/filterscripts:/omp-server-service/omp-server/filterscripts:rw
      - ./../../omp-server/gamemodes:/omp-server-service/omp-server/gamemodes:rw
      - ./../../omp-server/include:/omp-server-service/omp-server/include:rw
      - ./../../omp-server/logs:/omp-server-service/omp-server/logs:rw
      - ./../../omp-server/models:/omp-server-service/omp-server/models:rw
      - ./../../omp-server/pawno:/omp-server-service/omp-server/pawno:rw
      - ./../../omp-server/plugins:/omp-server-service/omp-server/plugins:rw
      - ./../../omp-server/scriptfiles:/omp-server-service/omp-server/scriptfiles:rw
      - ./../../omp-server/bans.json:/omp-server-service/omp-server/bans.json:rw
      - ./../../omp-server/config.json:/omp-server-service/omp-server/config.json:rw
      - ./../../omp-server/mysql.ini:/omp-server-service/omp-server/mysql.ini:rw
    environment:
      - MYSQL_HOST_AND_NAME_DATABASE=${MYSQL_HOST_AND_NAME_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - OMP_SERVER_PORT=${OMP_SERVER_PORT}
      - OMP_SERVER_PLAYERS=${OMP_SERVER_PLAYERS}
      - OMP_SERVER_RCON=${OMP_SERVER_RCON}
      - OMP_SERVER_WEBSITE=${OMP_SERVER_WEBSITE}
      - OMP_SERVER_PLUGINS=${OMP_SERVER_PLUGINS}
      - OMP_SERVER_GAMEMODES=${OMP_SERVER_GAMEMODES}
      - OMP_ENABLE_COMPILATION_GAMEMODES=${OMP_ENABLE_COMPILATION_GAMEMODES}
      - OMP_ENABLE_CONFIG_UPDATER=${OMP_ENABLE_CONFIG_UPDATER}
    command: ['sh', '-c', 'sleep 30 && unix-scripts/nodemon-watcher.sh']
    expose:
      - ${OMP_SERVER_PORT}
    ports:
      - ${OMP_SERVER_PORT}:${OMP_SERVER_PORT}/udp
    networks:
      - omp-network
    # depends_on:
    #   - omp-server-mysql
    #   - omp-server-pma
    tty: true
    stdin_open: true

networks:
  omp-network:
    name: omp-network
    external: true
